### PR TITLE
add: ESXi & VM Ansible Lockdowns

### PR DESCRIPTION
**Pull request by HerbBoy**
###Notes
- These roles are meant to be alternatives to the use of PowerShell for ESXi and VM STIG Lockdowns
- This is a roughly updated role. Extensive testing was not completed however linting and the logic used was tested.

### CODE REVIEW

**Comment by HerbBoy** [comment]
I forgot to develop the README's; If i commit to source will it get caught in this PR? Used to GitLab merges so unsure.

**Comment by rlakey** [comment]
Yea it should. Also was trying to figure out why there's a lot of files reporting as changed without any obvious changes? Maybe different formatting CRLF vs. LF?

**Comment by HerbBoy** [comment]
> 

I also saw that. I will resolve the CRLF to LF issue. As i know it causes issues.

Should have those implemented soon as well as more verbose READMEs

**Comment by HerbBoy** [comment]
@rlakey 

I added a lint job for the projects i created, it appears the runner does not install the `requirements.yml` is that define somewhere else?

also all files are LF, is that a problem? Unsure on why it would appear as different other then the fact i had to cp files and merge stuff together on myside. 

requesting review of the vcsa/playbook.yml (i incorporated new logic that we use and believe it would be a value add for folks.)

**Comment by rlakey** [comment]
I fixed all the files that were CRLF and updated to LF. I also added a .gitattributes so hopefully this won't be a problem again. Might need to rebase your branch to pick all of that up and then it shouldn't pick those files up as changes.

**Comment by rlakey** [comment]
Let's also keep the changes for this PR to the new playbook you are adding and address anything else separately.

**Comment by HerbBoy** [comment]
> Let's also keep the changes for this PR to the new playbook you are adding and address anything else separately.

image

Im still seeing CRLF

**Comment by HerbBoy** [comment]
image

updated.

**Comment by rlakey** [comment]
Still seeing some changes to VCSA ansible/inspec that shouldn't be there as well.

**Comment by HerbBoy** [comment]
> Still seeing some changes to VCSA ansible/inspec that shouldn't be there as well.

I did a complete rebase

**Comment by HerbBoy** [comment]
I cannot seem to understand why the runner cannot see the galaxy modules even when explicitly told to install the collections.

**Comment by HerbBoy** [comment]
still updating/resolving

**Comment by HerbBoy** [comment]
last outstanding item i can see is to fix the ansible-lint job to install the ansible collections so proper linting can be shown

**Comment by HerbBoy** [comment]
i am pretty stumped on why this ansible-lint runner does not work. @rlakey do you have any thoughts ?

**Comment by rlakey** [comment]
Looks like it's just a matter of where you are installing the collections which is a location ansible won't look for them.

This is from the output of the workflow run.

`Run ansible-galaxy collection install -f -r vsphere/7.0/vsphere/ansible/vmware-esxi-7.0-stig-ansible-hardening/requirements.yml -p collections
  ansible-galaxy collection install -f -r vsphere/7.0/vsphere/ansible/vmware-esxi-7.0-stig-ansible-hardening/requirements.yml -p collections
  shell: /usr/bin/bash -e {0}
Starting galaxy collection install process
Warning: : The specified collections path '/home/runner/work/dod-compliance-
and-automation/dod-compliance-and-automation/collections' is not part of the
configured Ansible collections paths
'/home/runner/.ansible/collections:/usr/share/ansible/collections'. The
installed collection won't be picked up in an Ansible run.`

I'd like to remove the VCSA playbook changes as well and handle that separately since I have some concerns that may not be suitable for everyone.

**Comment by HerbBoy** [comment]
> Looks like it's just a matter of where you are installing the collections which is a location ansible won't look for them.
> 
> This is from the output of the workflow run.
> 
> `Run ansible-galaxy collection install -f -r vsphere/7.0/vsphere/ansible/vmware-esxi-7.0-stig-ansible-hardening/requirements.yml -p collections ansible-galaxy collection install -f -r vsphere/7.0/vsphere/ansible/vmware-esxi-7.0-stig-ansible-hardening/requirements.yml -p collections shell: /usr/bin/bash -e {0} Starting galaxy collection install process Warning: : The specified collections path '/home/runner/work/dod-compliance- and-automation/dod-compliance-and-automation/collections' is not part of the configured Ansible collections paths '/home/runner/.ansible/collections:/usr/share/ansible/collections'. The installed collection won't be picked up in an Ansible run.`
> 
> I'd like to remove the VCSA playbook changes as well and handle that separately since I have some concerns that may not be suitable for everyone.

Well i have tried multiple locations that last one is where that error came from

**Comment by HerbBoy** [comment]
image

where i place them it is defaulted. yet still fails. makes zero sense.

**Comment by rlakey** [comment]
Ok i didn't catch the errors on those. Yea that's not making sense...can you add a command to run "ansible-galaxy collection list" after the install so we can see what it thinks is installed?

**Comment by HerbBoy** [comment]
added the commands. Also, can I ask why you dont feel the vcsa changes would be beneficial?

**Comment by rlakey** [comment]
Have you seen this discussion?  https://github.com/ansible/ansible-lint-action/discussions/113

**Comment by HerbBoy** [comment]
ok so it is seeing it as installed:

```
# /usr/share/ansible/collections/ansible_collections
Collection       Version
---------------- -------
ansible.posix    1.4.0  
community.vmware 3.1.0  

# /opt/pipx/venvs/ansible-core/lib/python3.10/site-packages/ansible_collections
Collection                    Version
----------------------------- -------
amazon.aws                    3.5.0  
ansible.netcommon             3.1.3  
```
But it is not in the main one

**Comment by HerbBoy** [comment]
so

```
# /opt/pipx/venvs/ansible-core/lib/python3.10/site-packages/ansible_collections
Collection                    Version
----------------------------- -------

...
community.vmware              3.1.0
```

I through it in here still failed.

**Comment by rlakey** [comment]
What did it look like when we had just the requirements.yml file? I haven't found the run yet under that scenario.

I can't add this one to the skip_list either since it doesn't allow it.

**Comment by HerbBoy** [comment]
> What did it look like when we had just the requirements.yml file? I haven't found the run yet under that scenario.
> 
> I can't add this one to the skip_list either since it doesn't allow it.

when i did not specify a path but called out the install via requirements.yml, it just shoved it into `/home/runner/.ansible/collections`

will do that so you can see

**Comment by HerbBoy** [comment]
i want to see what it looks like when i dont even call out the install of requirements, but github does not support, allow_failures like gitlab ci does

**Comment by HerbBoy** [comment]
So yeah warn_list made it all skip and not even check (might as well not even have the job then).

but what i find even more confusing, is in the test i ran in the esxi job i had it not call the install of requirements.yml but instead let ansible-lint do it (which it does) and:

```
/opt/pipx/venvs/ansible-core/lib/python3.10/site-packages/ansible_collections
Collection                    Version
----------------------------- -------
amazon.aws                    3.5.0  
ansible.netcommon        3.1.3  
ansible.posix                   1.4.0  
community.vmware        2.10.0 
```

And it has them both installed. When i run ansible lint on my box it has no issues, but the runner is having issues.

**Comment by rlakey** [comment]
The ansible-lint docs say the syntax-check is not something that be added to warn or skip.  https://ansible-lint.readthedocs.io/rules/syntax-check/

The manual install of collections won't work I believe because the runner for the workflow is the ubuntu container which clones the repo then runs the other parts but the ansible-lint part is a container itself so its downloading that and running the ansible-lint command inside of that which isn't where we installed the collections.

Was looking at the photon 3.0 playbook since it uses the posix collection as well and the only different from your requirements.yml and that one is the 3 --- at the top so maybe its something silly and those need to be removed?

**Comment by rlakey** [comment]
Or maybe the docs are wrong since you just added it and its a warning now.

**Comment by rlakey** [comment]
If removing the dashes from requirements.yml doesn't work we can probably make it work with the volumes the ansible-lint container is mounting and your previous install commands.

**Comment by HerbBoy** [comment]
> If removing the dashes from requirements.yml doesn't work we can probably make it work with the volumes the ansible-lint container is mounting and your previous install commands.

thats a good idea, and then pass that path as a additional env var

**Comment by HerbBoy** [comment]
Ok Using Volumes works, it was not the --- syntax (which also was used in the vcsa requirements.yml)

@rlakey I am requesting the following be added to the .ansible-lint warn_list:

- command-instead-of-shell - **Reason**: I use shell to initialize pwsh;
- jinja[spacing]  - **Reason**: I have tried to resolve this but simply it does not like how i have it setup and this does not cause any issues
- schema[vars]  - **Reason**: Does not like my long regex i guess. but it is for the stig and works.
-  var-naming - **Reason**: I built this out with the idea that each stig is tied to its STIG_ID.
- risky-file-permissions:  - **Reason**: expected.
- no-handler -  - **Reason**: Use of when statement seems legit to me and creating handlers seems overkill

**Comment by rlakey** [comment]
The var-naming stuff should pass if it was just lowercase.  ESXI_70_000001 to esxi_70_000001

**Comment by rlakey** [comment]
I'm not sure why the collection install worked either.  This folder doesn't exist on the ansible-lint container but it seems to have translated it to /github/workspace/collections.

`ANSIBLE_COLLECTIONS_PATH: '/home/runner/work/dod-compliance-and-automation/dod-compliance-and-automation/collections'`

`Set ANSIBLE_COLLECTIONS_PATH=/github/home/.cache/ansible-compat/21a323/collections:/github/workspace/collections:/github/workspace/collections`

On earlier runs it looked like this

`Set ANSIBLE_COLLECTIONS_PATH=/github/home/.cache/ansible-compat/21a323/collections:/github/home/.ansible/collections:/usr/share/ansible/collections`

**Comment by HerbBoy** [comment]
> I'm not sure why the collection install worked either. This folder doesn't exist on the ansible-lint container but it seems to have translated it to /github/workspace/collections.
> 
> `ANSIBLE_COLLECTIONS_PATH: '/home/runner/work/dod-compliance-and-automation/dod-compliance-and-automation/collections'`
> 
> `Set ANSIBLE_COLLECTIONS_PATH=/github/home/.cache/ansible-compat/21a323/collections:/github/workspace/collections:/github/workspace/collections`
> 
> On earlier runs it looked like this
> 
> `Set ANSIBLE_COLLECTIONS_PATH=/github/home/.cache/ansible-compat/21a323/collections:/github/home/.ansible/collections:/usr/share/ansible/collections`

Well the reason it is working is because the dir of the host container is:

```
"/home/runner/work/dod-compliance-and-automation/dod-compliance-and-automation":"/github/workspace"
```
Which translates to the random generated name inside the container later on. but that volume name is persistent

**Comment by rlakey** [comment]
> > I'm not sure why the collection install worked either. This folder doesn't exist on the ansible-lint container but it seems to have translated it to /github/workspace/collections.
> > `ANSIBLE_COLLECTIONS_PATH: '/home/runner/work/dod-compliance-and-automation/dod-compliance-and-automation/collections'`
> > `Set ANSIBLE_COLLECTIONS_PATH=/github/home/.cache/ansible-compat/21a323/collections:/github/workspace/collections:/github/workspace/collections`
> > On earlier runs it looked like this
> > `Set ANSIBLE_COLLECTIONS_PATH=/github/home/.cache/ansible-compat/21a323/collections:/github/home/.ansible/collections:/usr/share/ansible/collections`
> 
> Well the reason it is working is because the dir of the host container is:
> 
> ```
> "/home/runner/work/dod-compliance-and-automation/dod-compliance-and-automation":"/github/workspace"
> ```
> 
> Which translates to the random generated name inside the container later on. but that volume name is persistent
> 
> https://github.com/vmware/dod-compliance-and-automation/actions/runs/3528240728/jobs/5918137246#step:5:7
> 
> you can see exactly what is passed. I had to go with one that was not a hidden variable so that path made the most sense.

I would have thought we would have needed to pass /github/workspace/collections to the env variable.

**Comment by HerbBoy** [comment]
> > > I'm not sure why the collection install worked either. This folder doesn't exist on the ansible-lint container but it seems to have translated it to /github/workspace/collections.
> > > `ANSIBLE_COLLECTIONS_PATH: '/home/runner/work/dod-compliance-and-automation/dod-compliance-and-automation/collections'`
> > > `Set ANSIBLE_COLLECTIONS_PATH=/github/home/.cache/ansible-compat/21a323/collections:/github/workspace/collections:/github/workspace/collections`
> > > On earlier runs it looked like this
> > > `Set ANSIBLE_COLLECTIONS_PATH=/github/home/.cache/ansible-compat/21a323/collections:/github/home/.ansible/collections:/usr/share/ansible/collections`
> > 
> > 
> > Well the reason it is working is because the dir of the host container is:
> > ```
> > "/home/runner/work/dod-compliance-and-automation/dod-compliance-and-automation":"/github/workspace"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Which translates to the random generated name inside the container later on. but that volume name is persistent
> > https://github.com/vmware/dod-compliance-and-automation/actions/runs/3528240728/jobs/5918137246#step:5:7
> > you can see exactly what is passed. I had to go with one that was not a hidden variable so that path made the most sense.
> 
> I would have thought we would have needed to pass /github/workspace/collections to the env variable.

I did not see that being passed as a volume

**Comment by HerbBoy** [comment]
updated request to add the following to warn_list:

```
warn_list:  # or 'skip_list' to silence them completely
  - command-instead-of-shell  
  - experimental 
  - jinja[spacing]  
  - no-handler  
  - yaml[line-length] 
  - no-changed-when 
 ```

**Comment by rlakey** [comment]
> updated request to add the following to warn_list:
> 
> ```
> warn_list:  
>   - command-instead-of-shell  
>   - experimental 
>   - jinja[spacing]  
>   - no-handler  
>   - yaml[line-length] 
>   - no-changed-when 
> ```

We should be able to address most of these. I can help figure them out. Did you see the review i started on some of the code?

**Comment by HerbBoy** [comment]
> > updated request to add the following to warn_list:
> > ```
> > warn_list:  
> >   - command-instead-of-shell  
> >   - experimental 
> >   - jinja[spacing]  
> >   - no-handler  
> >   - yaml[line-length] 
> >   - no-changed-when 
> > ```
> 
> We should be able to address most of these. I can help figure them out. Did you see the review i started on some of the code?

Ok, I have a few solutions to a few of them but just need to test them out. I did not see the review. Its not appearing in this PR for me.

**Comment by HerbBoy** [comment]
@rlakey I have been working through validating each check today; corrected the linter issues but working through some logic issues.

Expect to have it complete COB monday.

**Comment by HerbBoy** [comment]
@rlakey all issues resolved.

**Pull request merged**
